### ISSUE TITLE
Warning: Object #<Object> has no method 'indexOf' Use --force to continue.

### ISSUE THREAD

**Issue by dvbeato** [itsnydell/grunt-ng-html2js#1]
I config my grunt file to use grunt-ng-html2js like README and when I run the command, I get an error:
grunt ng_html2js
Running "ng_html2js:files" (ng_html2js) task
Warning: Object #<Object> has no method 'indexOf' Use --force to continue.

## my config
``
ng_html2js: {
            options: {
                moduleName: 'safira-templates',
                moduleVar: 'safiraTemplates'
            },
            files: [{
                expand: true,
                cwd: 'src/directives/templates',
                src: ['**/*.html'],
                dest: 'sftemplates',
                ext: '.js'
            }]
},
``

**Comment by itsnydell** [comment]
You're using `:files` like it is a target, but it is not. Try using simply:

```
grunt ng_html2js
```

**Comment by dvbeato** [comment]
but how can I do to use with many files?

**Comment by itsnydell** [comment]
Run `grunt nghtml2js` if you code looks like this:
```
ng_html2js: {
    options: {
        moduleName: 'safira-templates',
        moduleVar: 'safiraTemplates'
    },
    files: [{
        expand: true,
        cwd: 'src/directives/templates',
        src: ['**/*.html'],
        dest: 'sftemplates',
        ext: '.js'
    }]
},
```

--

Run `grunt nghtml2js:main` if you code looks like this:
```
ng_html2js: {
    options: {
        moduleName: 'safira-templates',
        moduleVar: 'safiraTemplates'
    },
    main: {
        files: [{
            expand: true,
            cwd: 'src/directives/templates',
            src: ['**/*.html'],
            dest: 'sftemplates',
            ext: '.js'
        }]
    }
},
```

Notice that I wrapped your `files: [{}]` with `main: { ... }`. Main is a target (like a group), which allows you to run nghtml2js on that specific target. If you run `grunt nghtml2js` on the above, grunt will run every target you specify. The name `main` is not required, I just choose it since it's the only target. Each target should have a unique name. 

Since your code does not specify a target, you should run just `grunt nghtm2js`. Only use `nghtml2js:[target]` if you specify one. 

--

Please read [Grunt's documentation (http://gruntjs.com/configuring-tasks)](http://gruntjs.com/configuring-tasks) to better understand how to write grunt tasks.

**Comment by dvbeato** [comment]
worked using the specific configuration, like 'main', but the default configuration keep given same error
